#!/bin/bash
# Generate chat_ui_assets.ml from static/ files
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATIC_DIR="$REPO_ROOT/static"
OUTPUT="$REPO_ROOT/src/chat_ui_assets.ml"

escape_ocaml_string() {
  local content="$1"
  # Escape backslashes first, then double quotes, then embed as OCaml string
  printf '%s' "$content" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

embed_file() {
  local name="$1"
  local path="$2"
  local content
  content=$(cat "$path")
  local escaped
  escaped=$(escape_ocaml_string "$content")
  printf 'let %s = "%s"\n\n' "$name" "$escaped"
}

echo "Generating $OUTPUT from $STATIC_DIR..."

{
  echo "(* Auto-generated by scripts/embed_ui.sh - do not edit manually *)"
  echo ""
  embed_file "index_html" "$STATIC_DIR/index.html"
  embed_file "chat_css" "$STATIC_DIR/chat.css"
  embed_file "chat_js" "$STATIC_DIR/chat.js"
} > "$OUTPUT"

echo "Generated $OUTPUT"
